"""Install or remove automatic Skill analytics integrations."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

import scanner


HOOK_SCRIPT = Path(__file__).resolve().with_name("hook.py")
PROJECT_ROOT = Path(__file__).resolve().parent
ANALYTICS_SCRIPT = PROJECT_ROOT / "analytics.py"
INTEGRATIONS_DIR = PROJECT_ROOT / "integrations"
DEFAULT_DB_PATH = scanner.DEFAULT_DB_PATH
DEFAULT_OUTPUT_PATH = scanner.DATA_DIR / "dashboard.html"
STATUS_MESSAGE = "Updating local Skill analytics"
GENERATED_SENTINEL = "// Generated by codex-skill-analytics. Do not remove this line.\n"
PLATFORMS = ("codex", "claude", "opencode", "pi")


def _codex_home(value: str | os.PathLike[str] | None = None) -> Path:
    return Path(value or os.environ.get("CODEX_HOME") or Path.home() / ".codex").resolve()


def _claude_home(value: str | os.PathLike[str] | None = None) -> Path:
    return Path(
        value or os.environ.get("CLAUDE_CONFIG_DIR") or Path.home() / ".claude"
    ).expanduser().resolve()


def _opencode_config_dir(value: str | os.PathLike[str] | None = None) -> Path:
    return Path(
        value
        or os.environ.get("OPENCODE_CONFIG_DIR")
        or Path.home() / ".config" / "opencode"
    ).expanduser().resolve()


def _pi_home(value: str | os.PathLike[str] | None = None) -> Path:
    return Path(
        value
        or os.environ.get("PI_CODING_AGENT_DIR")
        or Path.home() / ".pi" / "agent"
    ).expanduser().resolve()


def _quote_windows(value: str | os.PathLike[str]) -> str:
    return '"' + str(Path(value).resolve()).replace('"', '\\"') + '"'


def hook_definition(
    executable: str | os.PathLike[str] = sys.executable,
    hook_script: str | os.PathLike[str] = HOOK_SCRIPT,
    *,
    db_path: str | os.PathLike[str] | None = None,
    output_path: str | os.PathLike[str] | None = None,
) -> dict[str, list[dict[str, object]]]:
    arguments = ""
    if db_path is not None:
        arguments += f" --db {_quote_windows(db_path)}"
    if output_path is not None:
        arguments += f" --output {_quote_windows(output_path)}"
    return {
        "hooks": [
            {
                "type": "command",
                "command": f"{_quote_windows(executable)} {_quote_windows(hook_script)}{arguments}",
                "statusMessage": STATUS_MESSAGE,
                "async": True,
            }
        ]
    }


def _read_config(path: Path) -> dict[str, object]:
    if not path.exists():
        return {"hooks": {}}
    value = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(value, dict):
        raise ValueError("hooks.json must contain a JSON object")
    return value


def _read_settings(path: Path) -> dict[str, object]:
    if not path.exists():
        return {"hooks": {}}
    value = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(value, dict):
        raise ValueError("settings.json must contain a JSON object")
    return value


def _stop_hooks(config: dict[str, object], *, create: bool) -> list[object] | None:
    hooks = config.get("hooks")
    if hooks is None and create:
        hooks = {}
        config["hooks"] = hooks
    if hooks is None:
        return None
    if not isinstance(hooks, dict):
        raise ValueError("hooks must be a JSON object")

    stop = hooks.get("Stop")
    if stop is None and create:
        stop = []
        hooks["Stop"] = stop
    if stop is None:
        return None
    if not isinstance(stop, list):
        raise ValueError("hooks.Stop must be a JSON array")
    return stop


def _write_config(path: Path, config: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(config, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _backup(path: Path) -> Path:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S-%f")
    backup = path.with_name(f"{path.name}.backup-{timestamp}")
    shutil.copy2(path, backup)
    return backup


def install(
    codex_home: str | os.PathLike[str] | None = None,
    *,
    executable: str | os.PathLike[str] = sys.executable,
    hook_script: str | os.PathLike[str] = HOOK_SCRIPT,
    db_path: str | os.PathLike[str] | None = None,
    output_path: str | os.PathLike[str] | None = None,
) -> tuple[bool, Path | None]:
    config_path = _codex_home(codex_home) / "hooks.json"
    config = _read_config(config_path)
    stop = _stop_hooks(config, create=True)
    assert stop is not None
    definition = hook_definition(
        executable, hook_script, db_path=db_path, output_path=output_path
    )
    if definition in stop:
        return False, None

    backup = _backup(config_path) if config_path.exists() else None
    if db_path is not None or output_path is not None:
        legacy = hook_definition(executable, hook_script)
        stop[:] = [item for item in stop if item != legacy]
    stop.append(definition)
    _write_config(config_path, config)
    return True, backup


def uninstall(
    codex_home: str | os.PathLike[str] | None = None,
    *,
    executable: str | os.PathLike[str] = sys.executable,
    hook_script: str | os.PathLike[str] = HOOK_SCRIPT,
    db_path: str | os.PathLike[str] | None = None,
    output_path: str | os.PathLike[str] | None = None,
) -> bool:
    config_path = _codex_home(codex_home) / "hooks.json"
    if not config_path.exists():
        return False
    config = _read_config(config_path)
    stop = _stop_hooks(config, create=False)
    if stop is None:
        return False

    definitions = {
        json.dumps(
            hook_definition(
                executable, hook_script, db_path=db_path, output_path=output_path
            ),
            sort_keys=True,
        )
    }
    if db_path is not None or output_path is not None:
        definitions.add(json.dumps(hook_definition(executable, hook_script), sort_keys=True))
    remaining = [
        item for item in stop
        if json.dumps(item, sort_keys=True) not in definitions
    ]
    if len(remaining) == len(stop):
        return False
    hooks = config["hooks"]
    assert isinstance(hooks, dict)
    hooks["Stop"] = remaining
    _write_config(config_path, config)
    return True


def claude_hook_definitions(
    executable: str | os.PathLike[str] = sys.executable,
    analytics_script: str | os.PathLike[str] = ANALYTICS_SCRIPT,
    *,
    db_path: str | os.PathLike[str] | None = None,
) -> dict[str, dict[str, object]]:
    handler = {
        "type": "command",
        "command": str(Path(executable).resolve()),
        "args": [
            str(Path(analytics_script).resolve()),
            "record",
            "--platform",
            "claude",
        ],
        "async": True,
    }
    if db_path is not None:
        handler["args"].extend(["--db", str(Path(db_path).resolve())])
    return {
        "PostToolUse": {"matcher": "Skill", "hooks": [handler]},
        "UserPromptExpansion": {"matcher": "", "hooks": [handler.copy()]},
    }


def _claude_groups(
    config: dict[str, object], event: str, *, create: bool
) -> list[object] | None:
    hooks = config.get("hooks")
    if hooks is None and create:
        hooks = {}
        config["hooks"] = hooks
    if hooks is None:
        return None
    if not isinstance(hooks, dict):
        raise ValueError("hooks must be a JSON object")
    groups = hooks.get(event)
    if groups is None and create:
        groups = []
        hooks[event] = groups
    if groups is None:
        return None
    if not isinstance(groups, list):
        raise ValueError(f"hooks.{event} must be a JSON array")
    return groups


def _install_claude(home: Path, db_path: Path) -> dict[str, object]:
    path = home / "settings.json"
    config = _read_settings(path)
    definitions = claude_hook_definitions(db_path=db_path)
    legacy = claude_hook_definitions()
    groups = {
        event: _claude_groups(config, event, create=True) for event in definitions
    }
    if all(definition in groups[event] for event, definition in definitions.items()):
        return _result("already_installed", path)
    backup = _backup(path) if path.exists() else None
    for event, definition in definitions.items():
        groups[event][:] = [group for group in groups[event] if group != legacy[event]]
        if definition not in groups[event]:
            groups[event].append(definition)
    _write_config(path, config)
    return _result("installed", path, backup)


def _uninstall_claude(home: Path, db_path: Path) -> dict[str, object]:
    path = home / "settings.json"
    if not path.exists():
        return _result("not_installed", path)
    config = _read_settings(path)
    definitions = claude_hook_definitions(db_path=db_path)
    legacy = claude_hook_definitions()
    changes: dict[str, list[object]] = {}
    for event, definition in definitions.items():
        groups = _claude_groups(config, event, create=False)
        if groups is not None:
            remaining = [
                group for group in groups
                if group not in (definition, legacy[event])
            ]
            if len(remaining) != len(groups):
                changes[event] = remaining
    if not changes:
        return _result("not_installed", path)
    backup = _backup(path)
    hooks = config["hooks"]
    assert isinstance(hooks, dict)
    hooks.update(changes)
    _write_config(path, config)
    return _result("removed", path, backup)


def _claude_status(home: Path, db_path: Path) -> str:
    path = home / "settings.json"
    if not path.exists():
        return "not_installed"
    try:
        config = _read_settings(path)
        definitions = claude_hook_definitions(db_path=db_path)
        legacy = claude_hook_definitions()
        present = []
        for event, definition in definitions.items():
            groups = _claude_groups(config, event, create=False)
            present.append(
                groups is not None
                and (definition in groups or legacy[event] in groups)
            )
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError):
        return "conflict"
    if all(present):
        return "installed"
    return "partial" if any(present) else "not_installed"


def _is_claude_group(group: object, event: str) -> bool:
    if not isinstance(group, dict):
        return False
    hooks = group.get("hooks")
    if not isinstance(hooks, list) or len(hooks) != 1 or not isinstance(hooks[0], dict):
        return False
    handler = hooks[0]
    arguments = handler.get("args")
    expected = claude_hook_definitions()[event]
    expected_handler = expected["hooks"][0]
    return (
        group.get("matcher") == expected["matcher"]
        and handler.get("type") == "command"
        and handler.get("command") == expected_handler["command"]
        and handler.get("async") is True
        and isinstance(arguments, list)
        and arguments[:4] == expected_handler["args"][:4]
        and (len(arguments) == 4 or (len(arguments) == 6 and arguments[4] == "--db"))
    )


def _render_integration(
    template: str,
    executable: str | os.PathLike[str],
    project_root: str | os.PathLike[str],
    db_path: str | os.PathLike[str] | None = None,
) -> str:
    rendered = template.replace(
        "__PYTHON_EXECUTABLE__", json.dumps(str(executable))
    ).replace("__PROJECT_ROOT__", json.dumps(str(project_root)))
    if db_path is not None:
        rendered = rendered.replace("__DATABASE_PATH__", json.dumps(str(db_path)))
    return GENERATED_SENTINEL + rendered


def _generated_target(platform: str, root: Path) -> tuple[Path, Path]:
    if platform == "opencode":
        return (
            root / "plugins" / "opencode-skill-analytics.js",
            INTEGRATIONS_DIR / "opencode-skill-analytics.js",
        )
    return (
        root / "extensions" / "pi-skill-analytics.ts",
        INTEGRATIONS_DIR / "pi-skill-analytics.ts",
    )


def _is_generated(path: Path) -> bool:
    try:
        with path.open("r", encoding="utf-8") as stream:
            return stream.readline() == GENERATED_SENTINEL
    except (OSError, UnicodeError):
        return False


def _generated_content(platform: str, root: Path, db_path: Path) -> tuple[Path, str]:
    path, template_path = _generated_target(platform, root)
    template = template_path.read_text(encoding="utf-8")
    return path, _render_integration(
        template, Path(sys.executable).resolve(), PROJECT_ROOT.resolve(), db_path
    )


def _install_generated(platform: str, root: Path, db_path: Path) -> dict[str, object]:
    path, rendered = _generated_content(platform, root, db_path)
    backup = None
    if path.exists():
        if not _is_generated(path):
            raise FileExistsError(f"refusing to overwrite unrelated file: {path}")
        if path.read_text(encoding="utf-8") == rendered:
            return _result("already_installed", path)
        backup = _backup(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rendered, encoding="utf-8")
    return _result("installed", path, backup)


def _uninstall_generated(platform: str, root: Path, db_path: Path) -> dict[str, object]:
    path, _ = _generated_target(platform, root)
    if not path.exists():
        return _result("not_installed", path)
    if not _is_generated(path):
        raise FileExistsError(f"refusing to remove unrelated file: {path}")
    content = path.read_text(encoding="utf-8")
    _, expected = _generated_content(platform, root, db_path)
    if content != expected and '"--db"' in content:
        return _result("not_installed", path)
    path.unlink()
    return _result("removed", path)


def _generated_status(platform: str, root: Path, db_path: Path) -> str:
    path, _ = _generated_target(platform, root)
    if not path.exists():
        return "not_installed"
    if not _is_generated(path):
        return "conflict"
    content = path.read_text(encoding="utf-8")
    _, expected = _generated_content(platform, root, db_path)
    if content == expected or '"--db"' not in content:
        return "installed"
    return "conflict"


def _generated_status_any(platform: str, root: Path) -> str:
    path, _ = _generated_target(platform, root)
    if not path.exists():
        return "not_installed"
    return "installed" if _is_generated(path) else "conflict"


def _result(status: str, path: Path, backup: Path | None = None) -> dict[str, object]:
    result: dict[str, object] = {"status": status, "path": str(path)}
    if backup is not None:
        result["backup"] = str(backup)
    return result


def _validate_platform(platform: str) -> None:
    if platform not in PLATFORMS:
        raise ValueError(f"unsupported platform: {platform}")


def install_platform(
    platform: str,
    *,
    codex_home: str | os.PathLike[str] | None = None,
    claude_home: str | os.PathLike[str] | None = None,
    opencode_config_dir: str | os.PathLike[str] | None = None,
    pi_home: str | os.PathLike[str] | None = None,
    db_path: str | os.PathLike[str] = DEFAULT_DB_PATH,
    output_path: str | os.PathLike[str] = DEFAULT_OUTPUT_PATH,
) -> dict[str, object]:
    _validate_platform(platform)
    database = Path(db_path).expanduser().resolve()
    output = Path(output_path).expanduser().resolve()
    if platform == "codex":
        home = _codex_home(codex_home)
        changed, backup = install(home, db_path=database, output_path=output)
        return _result(
            "installed" if changed else "already_installed",
            home / "hooks.json",
            backup,
        )
    if platform == "claude":
        return _install_claude(_claude_home(claude_home), database)
    if platform == "opencode":
        return _install_generated(platform, _opencode_config_dir(opencode_config_dir), database)
    return _install_generated(platform, _pi_home(pi_home), database)


def uninstall_platform(
    platform: str,
    *,
    codex_home: str | os.PathLike[str] | None = None,
    claude_home: str | os.PathLike[str] | None = None,
    opencode_config_dir: str | os.PathLike[str] | None = None,
    pi_home: str | os.PathLike[str] | None = None,
    db_path: str | os.PathLike[str] = DEFAULT_DB_PATH,
    output_path: str | os.PathLike[str] = DEFAULT_OUTPUT_PATH,
) -> dict[str, object]:
    _validate_platform(platform)
    database = Path(db_path).expanduser().resolve()
    output = Path(output_path).expanduser().resolve()
    if platform == "codex":
        home = _codex_home(codex_home)
        path = home / "hooks.json"
        if not path.exists() or integration_status(
            "codex", codex_home=home, db_path=database, output_path=output
        ) != "installed":
            return _result("not_installed", path)
        backup = _backup(path)
        uninstall(home, db_path=database, output_path=output)
        return _result("removed", path, backup)
    if platform == "claude":
        return _uninstall_claude(_claude_home(claude_home), database)
    if platform == "opencode":
        return _uninstall_generated(platform, _opencode_config_dir(opencode_config_dir), database)
    return _uninstall_generated(platform, _pi_home(pi_home), database)


def integration_status(
    platform: str,
    *,
    codex_home: str | os.PathLike[str] | None = None,
    claude_home: str | os.PathLike[str] | None = None,
    opencode_config_dir: str | os.PathLike[str] | None = None,
    pi_home: str | os.PathLike[str] | None = None,
    db_path: str | os.PathLike[str] | None = None,
    output_path: str | os.PathLike[str] | None = None,
) -> str:
    _validate_platform(platform)
    database = Path(db_path or DEFAULT_DB_PATH).expanduser().resolve()
    output = Path(output_path or DEFAULT_OUTPUT_PATH).expanduser().resolve()
    if platform == "codex":
        path = _codex_home(codex_home) / "hooks.json"
        if not path.exists():
            return "not_installed"
        try:
            config = _read_config(path)
            stop = _stop_hooks(config, create=False)
        except (OSError, UnicodeError, json.JSONDecodeError, ValueError):
            return "conflict"
        if db_path is None:
            base_command = hook_definition()["hooks"][0]["command"]
            installed = any(
                isinstance(group, dict)
                and isinstance(group.get("hooks"), list)
                and any(
                    isinstance(handler, dict)
                    and isinstance(handler.get("command"), str)
                    and (
                        handler["command"] == base_command
                        or handler["command"].startswith(base_command + " --db ")
                    )
                    for handler in group["hooks"]
                )
                for group in (stop or [])
            )
            return "installed" if installed else "not_installed"
        definitions = (
            hook_definition(db_path=database, output_path=output),
            hook_definition(),
        )
        return "installed" if stop is not None and any(
            definition in stop for definition in definitions
        ) else "not_installed"
    if platform == "claude":
        if db_path is None:
            path = _claude_home(claude_home) / "settings.json"
            if not path.exists():
                return "not_installed"
            try:
                config = _read_settings(path)
                present = []
                for event in ("PostToolUse", "UserPromptExpansion"):
                    groups = _claude_groups(config, event, create=False)
                    present.append(
                        groups is not None
                        and any(_is_claude_group(group, event) for group in groups)
                    )
            except (OSError, UnicodeError, json.JSONDecodeError, ValueError):
                return "conflict"
            if all(present):
                return "installed"
            return "partial" if any(present) else "not_installed"
        return _claude_status(_claude_home(claude_home), database)
    if platform == "opencode":
        if db_path is None:
            return _generated_status_any(platform, _opencode_config_dir(opencode_config_dir))
        return _generated_status(platform, _opencode_config_dir(opencode_config_dir), database)
    if db_path is None:
        return _generated_status_any(platform, _pi_home(pi_home))
    return _generated_status(platform, _pi_home(pi_home), database)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("install", "uninstall"))
    return parser


def main(argv: Iterable[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    if args.command == "install":
        changed, backup = install()
        if changed:
            print(f"Hook installed. Backup: {backup}" if backup else "Hook installed.")
        else:
            print("Hook already installed.")
    else:
        print("Hook removed." if uninstall() else "Hook was not installed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
